### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by ffffffelix** [chriswburke/gulp-sass-inline-svg#1]
Please can you update the npm package ? or upload your version to npm ?
Thanks

**Comment by chriswburke** [comment]
I'm not the original maintainer of this project, nor has the original maintainer been responsive. If you'd like to use this update in your own project you can do the following:

**In your package.json**
You can install the package from the git repo url, vs using the npm package
`
"gulp-sass-inline-svg": "git://github.com/chriswburke/gulp-sass-inline-svg.git",
`
